### ISSUE TITLE
Will pagination work correctly for upcoming and past events?

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack_site#143]
I've amended the view for events to separate upcoming from past dynamically.

Have not submitted more than 20 events to test yet but was wondering if you knew already whether the pagination would break with this set up?

**Comment by twinkarma** [comment]
Yes the pagination will just not work as pagination is performed on the result of `get_queryset()` which is currently being ignored as you've provided your own list of coming and past events to the `context`.

I've gone and fixed it now in #148 so that it becomes a single list instead:
![image](https://user-images.githubusercontent.com/11231792/135939187-f0975136-8b0e-463e-aa00-513bbe6b8479.png)

![image](https://user-images.githubusercontent.com/11231792/135939204-d768e07b-2629-455b-a8b9-bb559d2a7a82.png)

**Comment by annakrystalli** [comment]
Would it be possible for upcoming and past to have their own separate pagination?

**Comment by twinkarma** [comment]
It'll be a bit more work but yes it's possible.

**Comment by twinkarma** [comment]
@annakrystalli A question about showing events on the map. Should it show only events that's on the current page?
