### ISSUE TITLE
Problems to sign up and log in

### ISSUE THREAD

**Issue by SamCH93** [reprohack/reprohack_site#216]
Dear ReproHack team, 

thanks a lot for providing such an amazing infrastructure. 
I'm one of the organizers of the ReproHack that will take place next week in Bern. A student just mailed us that he was unable to register and propose a paper. I and another organizer tried ourselves and we were also unable to make an account, both of us receiving the following message:

Something went wrong :-(
Something went wrong while trying to load this website; please try again later.
If it is your site, you should check your logs to determine what the problem is.

(I tried it with Firefox and Chromium on Ubuntu 20.04). However, another organizer who had already created an account several weeks ago is able to log in. 
Do you know what could be the issue? 

Best wishes,
Samuel

**Comment by annakrystalli** [comment]
Thanks again @SamCH93 for reporting this really important bug. It was related the google API we use for sending emails which had a token revoked and this was causing sign up to fail (because the hub couldn't send an email to the user to verify their email.

I've technically fixed that problem but created a new one! (😭 story of my life!!) but I'm hoping to have everything resolved by the end of the day! Apologies for the delay. I'll ping on here again when it's fixed.

**Comment by annakrystalli** [comment]
FIXED!

All should be working again now. Many apologies again for the inconvenience and have a great time at the Swiss ReproHack!

**Comment by SamCH93** [comment]
Thank you so much for the fast handling of the issue :)
