### ISSUE TITLE
Hosting infrastructure

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack_site#27]
Invite Will and Bob?

Discuss:
- IT Services VMs
- Vagrant / Ansible Vs Docker

**Comment by willfurnass** [comment]
* Griff's experience is with Docker+Docker Compose so makes sense to stick with that
* Can deploy on ITS-provided VMs
   * Bind-mount network fileshares for database data and backups
* Can store images on DockerHub if keep secrets out of them
* Secrets management: `.env` file (separate for production and development, plus template for fresh instances) or Docker Secrets
   * Could persist secrets in RSE Keepass database?

**Comment by annakrystalli** [comment]
## Strategy

### Docker

Single VM with Docker containers for:
- DataBase
- Server
https://cookiecutter-django.readthedocs.io/en/latest/deployment-with-docker.html


Important to secure secrets: 
- https://docs.docker.com/engine/swarm/secrets/
- This Django config value? https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-SECRET_KEY
- 

Backup: Regular SQL dump to network fileshare

Cookie-cutter for django config



## Plan of Action:

- Request VM from IT Services

**Comment by annakrystalli** [comment]
## Plan of Action:

- [ ] Request VM from IT Services (AK)
  - UBUNTU 20.04
  - DB: PostgresQL
- [ ]

**Comment by willfurnass** [comment]
Further detail re the above:
 - Database, web app and web proxy (for TLS offload) containers to be linked/managed using Docker Compose.
 - Alternative to using Docker Secrets is to have a secure plain text file (`.env`) of key-value pairs on the Docker host that is read when containers are started.  Possibly simpler than Docker Secrets.
    - Could have separate files for production and development, plus a template for fresh instances
 - Can push images to DockerHub if config/secrets not baked into images.
 - 'Expose ports 443 & 80': via both local firewall _and_ institutional firewall; cannot generate certificates via LetsEncrypt unless LetsEncrypt servers on the Internet can access port 80 on the VM.
 - Can request VM from ITS for testing/staging first then request a second for production.
 - Can bind-mount network fileshares for database data and backups
 - If requesting a VM from IT Services you should let them know you want to run Docker on it.  I forgot that Docker is somewhat (but not entirely) incompatible with the firewall system used by some of the more recent Linux releases (Ubuntu 20.04 and CentOS 8.x).  For this reason Ubuntu 18.04 might be a better choice for the VM(s) as it uses the older `iptables` instead of the newer `nftables`.
 - @annakrystalli I think Griff is going to set up a service to periodically and automatically request TLS certs via LetsEncrypt so you don't need to request certs from IT Services.

**Comment by willfurnass** [comment]
Also: 
 - RSE team may want to look at using [Clair](https://coreos.com/clair/docs/latest/) or similar for periodic scanning for vulnerabilities

**Comment by griff-rees** [comment]
Building on @willfurnass's list: just a plain install with `docker-compose` is enough to start, assuming I have privileges to install other packages (not much, `git` + text editor + preferred `shell` config and permission to run `docker-compose`). [Clair documentation](https://access.redhat.com/documentation/en-us/red_hat_quay/2.9/html/manage_red_hat_quay/clair-initial-setup) does give a sense of what that might require if you'd like to lay the foundation from the start.

**Comment by willfurnass** [comment]
@griff-rees With TUOS VMWare VMs all 'owners' (with `sa_*` accounts) are able to run any command with sudo (plus password) so you'll be able to install RPMs/DEBs.  Should you not be using Ansible or similar to set up Docker Compose on the VM(s) I'd ask that you document the setup process.

**Comment by griff-rees** [comment]
I'm happy to give [Ansible](https://www.ansible.com/) a try.

**Comment by willfurnass** [comment]
@griff-rees I wouldn't worry too much about getting to grips with Ansible if you decide the only setup required is to enable one or two repos then install a couple of OS pkgs.

**Comment by griff-rees** [comment]
- @willfurnass fingers crossed that's enough, thanks for the reply.
- @annakrystalli 
  - Here are the config questions I will need to answer for the [cookiecutter](https://cookiecutter.readthedocs.io/en/latest/) configuration: (https://cookiecutter-django.readthedocs.io/en/latest/project-generation-options.html).
  - There's an example configuration prompt in the [readme](https://github.com/pydanny/cookiecutter-django#usage). 
  - If some of this is already answered in the current repo it'd be great to get links to those answers here. 
  - It's kind of hard to re-edit them once the template is generated as the configuration gets used in lots of places so it really helps to get all the questions right the first time (at least from my experience).

**Comment by annakrystalli** [comment]
OK I'm not sure how to answer some these and will need your input. So I'll try to get together as much as I can and let's as you suggested go through it together on friday.

In the meantime, it would be good if you could start having a look at the project as it is now and getting a feel for it. Perhaps have a look at this first? https://github.com/reprohack/reprohack_site/issues/9

**Comment by griff-rees** [comment]
Yeah it's a complicated process, hence thinking it best to do together. #9 is actually a significant case where it makes sense to use the [configuration `cookiecutter` provides](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/users/models.py), so don't think it's worth starting that until sorting a new `cookiecutter` branch to modify or inherit from.

**Comment by annakrystalli** [comment]
Ok that's totally fine. Maybe just seeing if you can add a draft review form then? Even small progress on setting up the models could be a useful starting point. 

If not, I'm happy for you to use discretion and pick anything that is feasible at this point to start work on just to get a feel for the code before our next meeting.

**Comment by annakrystalli** [comment]
Also I've added a [`CONTRIBUTING.md`](https://github.com/reprohack/reprohack_site/blob/master/CONTRIBUTING.md) with guidance on how we should work on GitHub 🙂

**Comment by annakrystalli** [comment]
project_name: Reprohack hub
project_slug: reprohackhub
description:  ReproHacks are reproducibilty hackathons where participants attempt to reproduce research papers from published code and data.
Describes your project and gets used in places like README.rst and such.
author_name: ?
email: reprohack.team@gmail.com
domain_name: reprohack.sheffield.ac.uk
version: ?
open_source_license: MIT?

**Comment by griff-rees** [comment]
So sorry to only discover this now, but I think PythonAnywhere isn't really an option for testing because they don't offer recent versions of `postgresql`  https://www.pythonanywhere.com/forums/topic/26601/ (and that's not one of the free options).

For the sake of a test example prior to creating a server for deploying in full `docker` fashion, maybe the quickest option is [`heroku`](https://cookiecutter-django.readthedocs.io/en/latest/deployment-on-heroku.html) [hobyist](https://www.heroku.com/pricing).

**Comment by annakrystalli** [comment]
@griff-rees also bought reprohack.com & reprohack.org.

Reimburse via expenses to RSE account

**Comment by annakrystalli** [comment]
This issue encompasses #22

**Comment by annakrystalli** [comment]
Article that might be useful as an approach to manage secrets.


https://blog.ktz.me/secret-management-with-docker-compose-and-ansible/

👀 @willfurnass ?

**Comment by willfurnass** [comment]
@annakrystalli Maybe; that's an interesting idea.  I'll have a think about whether it has significant advantages over using Docker Secrets.

**Comment by griff-rees** [comment]
Hey so just to update @willfurnass (and confirm generally with @annakrystalli): commit 265e1bb has closed #26 and #31 and now, finally, we've got an automated test suite up https://travis-ci.com/github/reprohack/reprohack_site. I see that as all part of infrastructure (can quibbled on the details but I think you get the idea), but having a server to test on too will be great.

**Comment by willfurnass** [comment]
@griff-rees We now have two (dev and live) Centos 8 VMs that you should be able to access using your TUOS sysadmin account.  You'll be able to run any command on these as root using sudo + your sysadmin password.  

The dev VM should be almost ready for you to use: Podman and podman-compose are now installed but the (nftables) firewall config, which is remotely managed by IT Services via Puppet, needs updating to allow port 80/443 (I've put in a request for that change).

Hopefully you shouldn't need to make many OS-level changes on this dev VM but if you do I'd be grateful if you could record those changes as Issues in a separate private repo that I'll send you a link to.

I'll send you a couple more details, inc the hostname, via email.
