### ISSUE TITLE
Environment variables in Django container not being properly set

### ISSUE THREAD

**Issue by davidwilby** [reprohack/reprohack_site#70]
There's some problem with the environment variables file and the `entrypoint` script for the `django` service, resulting in:

`CELERY_BROKER_URL` taking it's value from reprohack_site/.envs/.local/.django, due to the line:
```
CELERY_BROKER_URL=REDIS_URL
```
and not being set by `entrypoint` for some reason.

similarly, this line is not being executed correctly, so `DATABASE_URL` is not set, meaning that a whole range of django db commands can't be run incl. `createsuperuser` and `migrate`
```shell
export DATABASE_URL="postgis://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
```

**Comment by willfurnass** [comment]
I don't see how that line can be right: seems that it should really be something like:
```sh
CELERY_BROKER_URL="${REDIS_URL}"
```

**Comment by willfurnass** [comment]
Re the `DATABASE_URL` not being set: this looks pertinent: https://github.com/pydanny/cookiecutter-django/issues/2848

**Comment by davidwilby** [comment]
`CELERY_BROKER_URL=REDIS_URL` is in the env variable file, but there's a note elsewhere (I think in the [entrypoint](https://github.com/reprohack/reprohack_site/blob/master/compose/production/django/entrypoint)) about how you can't do variable expansion in env variable files.

But it seemed to me that when running the [local stack](https://github.com/reprohack/reprohack_site/blob/master/compose/local/django/Dockerfile) that the entrypoint script was not executing correctly as none of the environment variables set therein were actually set.

**Comment by griff-rees** [comment]
If memory serves stuff of this ilk came up when trying to sort this:

https://github.com/pydanny/cookiecutter-django/issues/1888
https://github.com/pydanny/cookiecutter-django/issues/2712
https://github.com/pydanny/cookiecutter-django/issues/2413#issuecomment-619628376

so it may be possible to alter the configuration, perhaps in line with this change: https://github.com/pydanny/cookiecutter-django/pull/2674

**Comment by Joe-Heffer-Shef** [comment]
Is the `django` container running the `/entrypoint` script?

I ask because the compose file defines the `command` option (which is equivalent to the CMD statement in a Dockerfile) like this `command: /start` as shown here https://github.com/reprohack/reprohack_site/blob/dev/local.yml#L24

The `/start` script doesn't set the `DATABASE_URL` environment variable.

I believe that Docker Compose will only use the entrypoint/ENTRYPOINT script when using `docker-compose run` and will run the command/CMD script when using `docker-compose up`.

https://goinbigdata.com/docker-run-vs-cmd-vs-entrypoint/#:~:text=ENTRYPOINT%20instruction%20allows%20you%20to,runs%20with%20command%20line%20parameters.

> ENTRYPOINT instruction allows you to configure a container that will run as an executable. It looks similar to CMD, because it also allows you to specify a command with parameters.

**Comment by Joe-Heffer-Shef** [comment]
By the way, passwords should probably not be stored in an environment variable.

See: [Manage sensitive data with Docker secrets](https://docs.docker.com/engine/swarm/secrets/)

**Comment by Joe-Heffer-Shef** [comment]
Proposed fix https://github.com/Joe-Heffer-Shef/reprohack_site/commit/9747be2ba32c1d86394ca0f1921b633208d7b7a0
