### ISSUE TITLE
Create richer user model

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack_site#9]
Include:
- [x] orchid id
- [x] afilliation
- [x] twitter
- [x] github

Authors should also have global fields:
- [x] public
- [x] contact
- [x] feedback

**Comment by JamesVStone** [comment]
Would you like the twitter/github/OrchedID information to be an OAuth (verified)  or just a string containing an account ID? @annakrystalli

**Comment by annakrystalli** [comment]
Hello @JamesVStone ! 
- twitter/github etc are fine as just text.  
- Orchid is also fine as text for now. Orchid IDs have a specific format, eg: `0000-0002-1825-0097`. If the form could validate entries against this sort of pattern, that would be great! But no worries if that's too complicated

**Comment by annakrystalli** [comment]
A custom user model has now been created. 

Global setting for authors not required (keep those associated with individual papers)

However, updating user does not currently work 😢

**Comment by cyncyncyn** [comment]
We were working with @flor14 with the sign up feature, as It wasn't working. 
As I understand, I don't  think that a custom user model is needed, because as far as I understand, the way the user is authenticated is not intended to be changed.

Changing the user model implies, for example, that you want to login with your email instead of a username.  
I think that what could be useful is extending the user model https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#extending-the-existing-user-model

We weren't able to finish the signup with the extended model because we run out of time today.
